/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/extract": {
    /** Extract */
    post: operations["extract_api_extract_post"];
  };
  "/api/centros/resolver": {
    /** Resolver */
    post: operations["resolver_api_centros_resolver_post"];
  };
  "/api/centros/ip-irc": {
    /** Ip Irc */
    get: operations["ip_irc_api_centros_ip_irc_get"];
  };
  "/api/derivacion/generar": {
    /** Generar */
    post: operations["generar_api_derivacion_generar_post"];
  };
  "/api/catalogo/medidas": {
    /** Medidas */
    get: operations["medidas_api_catalogo_medidas_get"];
  };
  "/api/catalogo/delitos": {
    /** Delitos */
    get: operations["delitos_api_catalogo_delitos_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Adolescente */
    Adolescente: {
      /** Nombre */
      nombre: string;
      /** Run */
      run: string;
      genero?: components["schemas"]["Genero"] | null;
      /** Domicilio */
      domicilio?: string | null;
      /** Comuna */
      comuna?: string | null;
    };
    /** AdultoResponsable */
    AdultoResponsable: {
      /** Nombre */
      nombre?: string | null;
      /** Telefono */
      telefono?: string | null;
    };
    /** AudienciaPII */
    AudienciaPII: {
      /**
       * Fecha
       * Format: date
       */
      fecha: string;
      /**
       * Hora
       * Format: time
       * @default 11:00:00
       */
      hora?: string;
      /**
       * Sala
       * @default 802
       */
      sala?: string;
      /**
       * Piso
       * @default 8°
       */
      piso?: string;
      /**
       * Edificio
       * @default E
       */
      edificio?: string;
    };
    /** Body_extract_api_extract_post */
    Body_extract_api_extract_post: {
      /** Files */
      files: string[];
    };
    /** CasoDerivacion */
    CasoDerivacion: {
      adolescente: components["schemas"]["Adolescente"];
      causa: components["schemas"]["Causa"];
      medida: components["schemas"]["Medida"];
      adulto?: components["schemas"]["AdultoResponsable"] | null;
      /** Duracion */
      duracion?: string | null;
      /** Abonos */
      abonos?: string | null;
      audiencia_pii?: components["schemas"]["AudienciaPII"] | null;
      /** Observaciones */
      observaciones?: string | null;
      centro: components["schemas"]["CentroAsignado"];
    };
    /** Causa */
    Causa: {
      /** Tribunal */
      tribunal?: string | null;
      /** Tipo Resolucion */
      tipo_resolucion?: string | null;
      /** Ruc */
      ruc?: string | null;
      /** Rit */
      rit?: string | null;
      /** Delito */
      delito?: string | null;
      /** Fecha Resolucion */
      fecha_resolucion?: string | null;
      /**
       * Art 37 Bis
       * @default false
       */
      art_37_bis?: boolean;
    };
    /** CentroAsignado */
    CentroAsignado: {
      /** Nombre */
      nombre: string;
      /** Director */
      director: string;
      /** Mail */
      mail: string;
      /** Telefono */
      telefono: string;
      /** Direccion */
      direccion?: string | null;
      /** Tipo */
      tipo?: ("Priorizada" | "No priorizada") | null;
    };
    /**
     * CentroIPIRC
     * @enum {string}
     */
    CentroIPIRC: "San_Joaquin" | "San_Bernardo" | "Til_Til" | "Santiago";
    /** ExtractionResult */
    ExtractionResult: {
      /** Candidatos */
      candidatos: components["schemas"]["Adolescente"][];
      causa: components["schemas"]["Causa"];
      adulto: components["schemas"]["AdultoResponsable"];
      medida_sugerida: components["schemas"]["Medida"] | null;
      /**
       * Warnings
       * @default []
       */
      warnings?: string[];
    };
    /** GenerarDerivacionRequest */
    GenerarDerivacionRequest: {
      caso: components["schemas"]["CasoDerivacion"];
      /** Profesional */
      profesional: string;
      /**
       * Fecha Emision
       * Format: date
       */
      fecha_emision: string;
    };
    /**
     * Genero
     * @enum {string}
     */
    Genero: "Masculino" | "Femenino";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Medida
     * @enum {string}
     */
    Medida: "MCA" | "SBC" | "LAS" | "LAE" | "LAEIP" | "IP" | "IRC" | "PSA" | "SALIDAS_ALTERNATIVAS";
    /** MedidaCatalogoItem */
    MedidaCatalogoItem: {
      sigla: components["schemas"]["Medida"];
      /** Nombre */
      nombre: string;
      /** Base Legal */
      base_legal: string;
      /** Estado */
      estado: string;
    };
    /** ResolverCentroRequest */
    ResolverCentroRequest: {
      medida: components["schemas"]["Medida"];
      /** Comuna */
      comuna: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Extract */
  extract_api_extract_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_extract_api_extract_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExtractionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Resolver */
  resolver_api_centros_resolver_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolverCentroRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CentroAsignado"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Ip Irc */
  ip_irc_api_centros_ip_irc_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: components["schemas"]["CentroAsignado"];
          };
        };
      };
    };
  };
  /** Generar */
  generar_api_derivacion_generar_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerarDerivacionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Medidas */
  medidas_api_catalogo_medidas_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MedidaCatalogoItem"][];
        };
      };
    };
  };
  /** Delitos */
  delitos_api_catalogo_delitos_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
}
